package manage

import (
	"fmt"
	"os"
	"strings"

	"github.com/backpack/backpack/internal/app"
)

// TunnelSpec is the full description of a tunnel used to render a TOML config.
type TunnelSpec struct {
	Name      string
	Role      string // "server" (Iran/edge that exposes ports) or "client" (kharej/origin)
	Transport string // tcp, udp, ws, wss, tcpmux, wsmux, wssmux

	BindAddr   string   // server: listen address for the tunnel control channel
	RemoteAddr string   // client: address of the server tunnel port
	Token      string   // shared secret
	Ports      []string // server: exposed/forwarded ports

	Nodelay        bool
	Heartbeat      int
	KeepAlive      int
	ChannelSize    int
	ConnectionPool int
	AggressivePool bool
	AcceptUDP      bool
	LogLevel       string

	// SMUX / multiplexed transports
	MuxCon          int
	MuxVersion      int
	MuxFrameSize    int
	MuxRecvBuffer   int
	MuxStreamBuffer int

	// Throughput / latency tuning
	MSS      int // TCP max segment size (0 = auto)
	SoRcvBuf int // per-socket receive buffer (bytes)
	SoSndBuf int // per-socket send buffer (bytes)

	// Sniffer web panel
	Sniffer bool
	WebPort int

	// TLS (server, wss/wssmux only)
	TLSCert string
	TLSKey  string

	// Edge/CDN IP override (client, websocket transports only)
	EdgeIP string
}

// writeTuning emits the throughput/latency knobs shared by server and client.
func (s TunnelSpec) writeTuning(p func(string, ...any)) {
	if s.MSS > 0 {
		p("mss = %d\n", s.MSS)
	}
	if s.SoRcvBuf > 0 {
		p("so_rcvbuf = %d\n", s.SoRcvBuf)
	}
	if s.SoSndBuf > 0 {
		p("so_sndbuf = %d\n", s.SoSndBuf)
	}
}

// isMux reports whether a transport multiplexes over SMUX.
func isMux(t string) bool {
	return t == "tcpmux" || t == "wsmux" || t == "wssmux"
}

// isWS reports whether a transport rides over websocket.
func isWS(t string) bool {
	return t == "ws" || t == "wss" || t == "wsmux" || t == "wssmux"
}

// needsTLS reports whether a transport terminates TLS on the server and
// therefore requires a certificate/key pair.
func needsTLS(t string) bool {
	return t == "wss" || t == "wssmux"
}

// validTransport reports whether t is one of the engine's supported transports.
func validTransport(t string) bool {
	switch t {
	case "tcp", "tcpmux", "udp", "ws", "wss", "wsmux", "wssmux":
		return true
	}
	return false
}

// Render returns the TOML representation of the tunnel.
func (s TunnelSpec) Render() string {
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	b.WriteString("# Generated by backpack — do not edit while the service is running.\n")
	p("# name = \"%s\"\n\n", s.Name)

	if s.Role == "server" {
		b.WriteString("[server]\n")
		p("bind_addr = %q\n", s.BindAddr)
		p("transport = %q\n", s.Transport)
		p("token = %q\n", s.Token)
		p("channel_size = %d\n", s.ChannelSize)
		p("keepalive_period = %d\n", s.KeepAlive)
		p("nodelay = %t\n", s.Nodelay)
		p("heartbeat = %d\n", s.Heartbeat)
		p("log_level = %q\n", s.LogLevel)
		s.writeTuning(p)
		if s.Transport == "tcp" {
			// accept_udp is only honoured by the plain TCP transport in the engine.
			p("accept_udp = %t\n", s.AcceptUDP)
		}
		if needsTLS(s.Transport) {
			p("tls_cert = %q\n", s.TLSCert)
			p("tls_key = %q\n", s.TLSKey)
		}
		if isMux(s.Transport) {
			p("mux_con = %d\n", s.MuxCon)
			p("mux_version = %d\n", s.MuxVersion)
			p("mux_framesize = %d\n", s.MuxFrameSize)
			p("mux_recievebuffer = %d\n", s.MuxRecvBuffer)
			p("mux_streambuffer = %d\n", s.MuxStreamBuffer)
		}
		p("sniffer = %t\n", s.Sniffer)
		if s.WebPort > 0 {
			p("web_port = %d\n", s.WebPort)
		}
		b.WriteString("ports = [\n")
		for _, port := range s.Ports {
			p("    %q,\n", port)
		}
		b.WriteString("]\n")
		return b.String()
	}

	// client
	b.WriteString("[client]\n")
	p("remote_addr = %q\n", s.RemoteAddr)
	p("transport = %q\n", s.Transport)
	p("token = %q\n", s.Token)
	p("connection_pool = %d\n", s.ConnectionPool)
	p("aggressive_pool = %t\n", s.AggressivePool)
	p("keepalive_period = %d\n", s.KeepAlive)
	p("nodelay = %t\n", s.Nodelay)
	p("retry_interval = %d\n", 3)
	p("dial_timeout = %d\n", 10)
	p("log_level = %q\n", s.LogLevel)
	s.writeTuning(p)
	if isWS(s.Transport) && s.EdgeIP != "" {
		p("edge_ip = %q\n", s.EdgeIP)
	}
	if isMux(s.Transport) {
		p("mux_session = %d\n", s.MuxCon)
		p("mux_version = %d\n", s.MuxVersion)
		p("mux_framesize = %d\n", s.MuxFrameSize)
		p("mux_recievebuffer = %d\n", s.MuxRecvBuffer)
		p("mux_streambuffer = %d\n", s.MuxStreamBuffer)
	}
	p("sniffer = %t\n", s.Sniffer)
	if s.WebPort > 0 {
		p("web_port = %d\n", s.WebPort)
	}
	return b.String()
}

// Save writes the config file, the systemd unit, reloads systemd and starts
// the tunnel. It returns the service name on success.
func (s TunnelSpec) Save() (string, error) {
	if err := os.MkdirAll(app.ConfigDir, 0755); err != nil {
		return "", err
	}
	if err := os.WriteFile(app.ConfigPath(s.Name), []byte(s.Render()), 0644); err != nil {
		return "", err
	}
	if err := writeUnit(s.Name); err != nil {
		return "", err
	}
	if err := DaemonReload(); err != nil {
		return "", err
	}
	service := app.ServiceName(s.Name)
	if err := StartService(service); err != nil {
		return service, err
	}
	return service, nil
}
