package manage

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/backpack/backpack/config"
	"github.com/backpack/backpack/internal/app"
	"github.com/backpack/backpack/internal/engine"
	"github.com/backpack/backpack/internal/instanceid"
	"github.com/backpack/backpack/internal/tui"
)

func renderDirect(mappings []config.ForwardMapping) string {
	var b strings.Builder
	b.WriteString("# Generated by backpack. Direct forwarding is owned by this instance.\n")
	b.WriteString("engine = \"iptables\"\n\n[forward]\n")
	for _, m := range mappings {
		b.WriteString("\n[[forward.mappings]]\n")
		fmt.Fprintf(&b, "listen_address = %q\nlisten_ports = %q\ntarget_address = %q\ntarget_ports = %q\n", m.ListenAddress, m.ListenPorts, m.TargetAddress, m.TargetPorts)
		quoted := make([]string, len(m.Protocols))
		for i, p := range m.Protocols {
			quoted[i] = fmt.Sprintf("%q", strings.ToLower(p))
		}
		fmt.Fprintf(&b, "protocols = [%s]\n", strings.Join(quoted, ", "))
	}
	return b.String()
}

func directConfig(m []config.ForwardMapping) *config.Config {
	return &config.Config{Engine: config.EngineIPTables, Forward: config.ForwardConfig{Mappings: m}}
}

func validateDirectCandidate(name string, mappings []config.ForwardMapping) error {
	cfg := directConfig(mappings)
	if err := cfg.ValidateStructure(); err != nil {
		return err
	}
	p, err := engine.Resolve(cfg)
	if err != nil {
		return err
	}
	return p.Validate(context.Background(), engine.Request{ConfigPath: app.ConfigPath(name), Config: cfg})
}

func saveDirect(name string, mappings []config.ForwardMapping) (string, error) {
	cfg := directConfig(mappings)
	if err := cfg.ValidateStructure(); err != nil {
		return "", err
	}
	if err := os.MkdirAll(app.ConfigDir, 0o755); err != nil {
		return "", err
	}
	path, service := app.ConfigPath(name), app.ServiceName(name)
	identity, err := instanceid.Create(path)
	if err != nil {
		return "", fmt.Errorf("create direct instance identity: %w", err)
	}
	committed := false
	defer func() {
		if committed {
			return
		}
		_ = DisableService(service)
		if p, err := engine.Resolve(cfg); err == nil {
			_ = p.Cleanup(context.Background(), engine.Request{ConfigPath: path, Config: cfg})
		}
		removeUnit(name)
		_ = os.Remove(path)
		_ = os.Remove(instanceid.Path(path))
		_ = os.Remove(filepath.Join(app.ConfigDir, "forward-state", identity.InstanceID+".json"))
		_ = os.Remove(filepath.Join(app.ConfigDir, name+".metrics.json"))
		_ = DaemonReload()
	}()
	if err := validateDirectCandidate(name, mappings); err != nil {
		return "", err
	}
	if err := app.WriteFileAtomic(path, []byte(renderDirect(mappings)), 0o600); err != nil {
		return "", err
	}
	if err := writeUnit(name); err != nil {
		return "", err
	}
	if err := DaemonReload(); err != nil {
		return "", err
	}
	if err := StartService(service); err != nil {
		return "", err
	}
	provider, _ := engine.Resolve(cfg)
	deadline := time.Now().Add(12 * time.Second)
	for time.Now().Before(deadline) {
		h, _ := provider.Health(context.Background(), engine.Request{ConfigPath: path, Config: cfg})
		if h.Ready {
			committed = true
			return service, nil
		}
		time.Sleep(500 * time.Millisecond)
	}
	return "", fmt.Errorf("direct desired state did not become ready")
}

func promptDirectMapping(existing *config.ForwardMapping) (config.ForwardMapping, bool) {
	m := config.ForwardMapping{}
	if existing != nil {
		m = *existing
	}
	for {
		raw := strings.TrimSpace(tui.PromptDefault("Target IP", m.TargetAddress))
		ip := net.ParseIP(raw)
		if ip == nil {
			tui.Error("Target must be an explicit IPv4 or IPv6 address.")
			continue
		}
		m.TargetAddress = ip.String()
		break
	}
	wildcard := "0.0.0.0"
	if net.ParseIP(m.TargetAddress).To4() == nil {
		wildcard = "::"
	}
	if m.ListenAddress == "" {
		m.ListenAddress = wildcard
	}
	m.ListenAddress = strings.TrimSpace(tui.PromptDefault("Listen address (wildcard means every local address)", m.ListenAddress))
	m.ListenPorts = strings.TrimSpace(tui.PromptDefault("Listen port or range", m.ListenPorts))
	m.TargetPorts = strings.TrimSpace(tui.PromptDefault("Target port or equal-length range", m.TargetPorts))
	idx := tui.ChooseOpt("Protocols:", []tui.Option{{Title: "TCP + UDP", Desc: "install both protocol mappings"}, {Title: "TCP", Desc: "TCP only"}, {Title: "UDP", Desc: "UDP only"}})
	switch idx {
	case 0:
		m.Protocols = []string{"tcp", "udp"}
	case 1:
		m.Protocols = []string{"tcp"}
	case 2:
		m.Protocols = []string{"udp"}
	default:
		return config.ForwardMapping{}, false
	}
	if err := config.ValidateForward(config.ForwardConfig{Mappings: []config.ForwardMapping{m}}); err != nil {
		tui.Error(err.Error())
		tui.PressEnter()
		return config.ForwardMapping{}, false
	}
	return m, true
}

func SetupDirect() {
	tui.Clear()
	tui.Title("Advanced Kernel Direct Forward")
	tui.Warn("Incoming TCP/UDP is DNATed directly to one fixed target with iptables.")
	tui.Warn("MASQUERADE means the target sees this ingress server as the source.")
	fmt.Println()
	name := uniqueName(tui.PromptDefault("Instance name", "direct-forward"))
	var mappings []config.ForwardMapping
	for {
		m, ok := promptDirectMapping(nil)
		if !ok {
			if len(mappings) == 0 {
				return
			}
			break
		}
		mappings = append(mappings, m)
		if !tui.Confirm("Add another mapping", false) {
			break
		}
	}
	if err := validateDirectCandidate(name, mappings); err != nil {
		tui.Error("Validation failed: " + err.Error())
		tui.PressEnter()
		return
	}
	fmt.Println()
	tui.Info("Rules to install:")
	for _, m := range mappings {
		fmt.Printf("  %s %s:%s -> %s:%s\n", strings.ToUpper(strings.Join(m.Protocols, "+")), m.ListenAddress, m.ListenPorts, m.TargetAddress, m.TargetPorts)
	}
	if !tui.Confirm("Create and start this direct-forward instance", true) {
		return
	}
	service, err := saveDirect(name, mappings)
	if err != nil {
		tui.Error("Failed: " + err.Error())
	} else {
		tui.Success("Direct forward created: " + service)
	}
	tui.PressEnter()
}

func applyDirect(name string, mappings []config.ForwardMapping) error {
	if err := validateDirectCandidate(name, mappings); err != nil {
		return err
	}
	path, service := app.ConfigPath(name), app.ServiceName(name)
	previous, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	wasActive := IsActive(service)
	if err = app.WriteFileAtomic(path, []byte(renderDirect(mappings)), 0o600); err != nil {
		return err
	}
	if err = RestartService(service); err != nil {
		revertSpec(path, previous, service, wasActive)
		return fmt.Errorf("direct instance failed to restart; reverted: %w", err)
	}
	deadline := time.Now().Add(12 * time.Second)
	for time.Now().Before(deadline) {
		cfg, e := config.LoadFile(path)
		if e == nil {
			p, _ := engine.Resolve(cfg)
			h, _ := p.Health(context.Background(), engine.Request{ConfigPath: path, Config: cfg})
			if h.Ready {
				return nil
			}
		}
		time.Sleep(500 * time.Millisecond)
	}
	revertSpec(path, previous, service, wasActive)
	return fmt.Errorf("direct desired state did not become ready; previous config was restored")
}

func editDirectMenu(name string) {
	for {
		cfg, err := config.LoadFile(app.ConfigPath(name))
		if err != nil {
			tui.Error(err.Error())
			tui.PressEnter()
			return
		}
		maps := append([]config.ForwardMapping(nil), cfg.Forward.Mappings...)
		opts := make([]tui.Option, 0, len(maps)+2)
		for i, m := range maps {
			opts = append(opts, tui.Option{Title: fmt.Sprintf("%d. %s:%s", i+1, m.ListenAddress, m.ListenPorts), Desc: fmt.Sprintf("%s -> %s:%s", strings.ToUpper(strings.Join(m.Protocols, "+")), m.TargetAddress, m.TargetPorts)})
		}
		opts = append(opts, tui.Option{Title: "Add mapping", Desc: "append another TCP/UDP mapping"}, tui.Option{Title: "Remove mapping", Desc: "select one to delete"})
		idx := tui.ChooseOpt("Select a mapping to edit, or an action:", opts)
		if idx < 0 {
			return
		}
		switch {
		case idx < len(maps):
			m, ok := promptDirectMapping(&maps[idx])
			if !ok {
				continue
			}
			maps[idx] = m
		case idx == len(maps):
			m, ok := promptDirectMapping(nil)
			if !ok {
				continue
			}
			maps = append(maps, m)
		default:
			if len(maps) <= 1 {
				tui.Error("At least one mapping is required.")
				tui.PressEnter()
				continue
			}
			rm := tui.ChooseOpt("Remove which mapping?", opts[:len(maps)])
			if rm < 0 {
				continue
			}
			maps = append(maps[:rm], maps[rm+1:]...)
		}
		if err := applyDirect(name, maps); err != nil {
			tui.Error(err.Error())
		} else {
			tui.Success("Direct mappings updated and verified.")
		}
		tui.PressEnter()
	}
}
